# Generated by Django 4.0.3 on 2023-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_customer_id_loan_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('F', 'FAILED'), ('P', 'POSITIVE'), ('N', 'NEGATIVE')], max_length=1)),
            ],
        ),
    ]
