# Generated by Django 4.0.3 on 2023-04-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Account',
        ),
    ]
