# Generated by Django 4.0.3 on 2023-04-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_customer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer',
            new_name='account',
        ),
    ]
